definitions:
  notification.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  notification.SendNotificationRequest:
    properties:
      message:
        type: string
      type:
        type: string
      user_id:
        type: string
    required:
    - message
    - type
    - user_id
    type: object
  notification.StatusResponse:
    properties:
      status:
        type: string
    type: object
info:
  contact: {}
  title: Modak Challenge API
  version: "1.0"
paths:
  /v1/notifications/send:
    post:
      description: Sends a notification to a user respecting per-type rate limits
      parameters:
      - description: Notification payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/notification.SendNotificationRequest'
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/notification.StatusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/notification.ErrorResponse'
        "429":
          description: Too Many Requests
          schema:
            $ref: '#/definitions/notification.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/notification.ErrorResponse'
      summary: Send a notification
      tags:
      - notifications
swagger: "2.0"
